<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'L\'account è già stato disabilitato',
    'Account successfully disconnected' => 'Account disconnesso con successo',
    'Account updated' => 'Account aggiornato',
    'Bind account' => 'Collega account',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Non è possibile disconnettere il metodo di autenticazione singolo. Si prega di compilare l\'email e la password e riprovare',
    'Cancel' => 'Annulla',
    'Changing your email requires email confirmation' => 'La modifica della tua email richiede la conferma dell\'email',
    'Connected' => 'Collegato',
    'Create Time' => 'Data di creazione',
    'Currency' => 'Valuta',
    'Decimal Separator' => 'Separatore decimale',
    'Disconnect' => 'Disconnetti',
    'Full Name' => 'Nome completo',
    'Go home' => 'Torna alla pagina iniziale',
    'Go to my account' => 'Vai al mio account',
    'Guests can not disconnect accounts' => 'Gli ospiti non possono disconnettere gli account',
    'ID' => 'ID',
    'Instructions to reset your password have been sent' => 'Le istruzioni per reimpostare la password sono state inviate',
    'Invalid key' => 'Chiave non valida',
    'Keychain' => 'Portachiavi',
    'Language' => 'Lingua',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Collegare gli account dei social network (possono essere più di uno) al tuo account ti permetterà di accedere con un solo clic.',
    'Log in here' => 'Accedi qui',
    'Login' => 'Accesso',
    'Password has been reset' => 'La password è stata reimpostata',
    'Passwords do not match' => 'Le password non corrispondono',
    'Pending email confirmation: [ {newEmail} ]' => 'Conferma dell\'email in sospeso: [ {newEmail} ]',
    'Profile' => 'Profilo',
    'Resend' => 'Invia nuovamente',
    'Reset' => 'Resetta',
    'Start Page' => 'Pagina di avvio',
    'Submit' => 'Invia',
    'This account has already been connected' => 'Questo account è già stato collegato',
    'Update' => 'Aggiorna',
    'Update Time' => 'Data di aggiornamento',
    'User ID' => 'ID Utente',
    'Yii 2 User' => 'Utente Yii 2',
    'Your email [ {email} ] has been confirmed' => 'La tua email [ {email} ] è stata confermata',
    'or' => 'o',
    '{attribute} can contain only letters, numbers, and "_"' => '{attribute} può contenere solo lettere, numeri e "_"',
    'Сan not disconnect a foreign account' => 'Impossibile disconnettere un account esterno',
];